[build]
  Command = "jekyll build"
  Publish = "_site"

[template.environment]
  SL9_CLIENT_NAME = "Shoreline Media Marketing"
  SL9_CUSTOM_LOGO = "//shorelinemedia.github.io/images/Shoreline-Media1.neuquant.png"
  SL9_PRIMARY_COLOR = "#0099CC"
  SL9_BG_COLOR = "#587E9D"
  SL9_UP_MESSAGE = "<p>We apologize for the inconvenience. We'll be back online shortly. In the meantime, please call <a href='tel:888-591-8205'>888-591-8205</a> if you need immediate assistance.</p>"
  SL9_MAINTENANCE_MESSAGE = "We are currently upgrading our website"
